### ISSUE TITLE
✅ Ruby Catalog of Things App - Kanban Board Setup 🎫

### ISSUE THREAD

**Issue by ITurres** [ITurres/catalog_of_things#22]
## Hi there! We are @ITurres and @demesameneshoa,

- Team Member 1: @demesameneshoa 
- Team Member 2: @ITurres
- Team Member 3: @ITurres & @demesameneshoa (divided tasks).

💎 [Ruby Project Kanban Board](https://github.com/ITurres/catalog_of_things/projects/1)

**Comment by ademibowale** [comment]
Hi @ITurres @demesameneshoa , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- Each card on the board has:a descriptive title✔️
- a description of the task.✔️
- Each card on the board has Descriptive commit messages ✔️ 
- columns in students' Kanban board are the same as in the template.✔️
- Good use of Gitflow ✔️

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)




- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ITurres** [comment]
Great then, thank you @ademibowale!
